export type PlayerStats = {
  id: number;
  playerId: number;
  sleeper_player_id: number;
  year: number;
  week: number;
  blk_kick?: number;
  bonus_fd_qb?: number;
  bonus_fd_rb?: number;
  bonus_fd_te?: number;
  bonus_fd_wr?: number;
  bonus_pass_cmp_25?: number;
  bonus_pass_yd_300?: number;
  bonus_rec_rb?: number;
  bonus_rec_te?: number;
  bonus_rec_wr?: number;
  bonus_rec_yd_100?: number;
  bonus_rush_att_20?: number;
  bonus_rush_rec_yd_100?: number;
  bonus_rush_yd_100?: number;
  bonus_sack_2p?: number;
  bonus_tkl_10p?: number;
  cmp_pct?: number;
  def_3_and_out?: number;
  def_4_and_stop?: number;
  def_forced_punts?: number;
  def_kr?: number;
  def_kr_lng?: number;
  def_kr_yd?: number;
  def_kr_ypa?: number;
  def_pass_def?: number;
  def_pr?: number;
  def_pr_lng?: number;
  def_pr_yd?: number;
  def_pr_ypa?: number;
  def_snp?: number;
  def_st_ff?: number;
  def_st_fum_rec?: number;
  def_st_tkl_solo?: number;
  def_td?: number;
  down_3_att?: number;
  down_3_conv?: number;
  down_3_pct?: number;
  down_4_att?: number;
  down_4_conv?: number;
  down_4_pct?: number;
  fan_pts_allow?: number;
  fan_pts_allow_k?: number;
  fan_pts_allow_qb?: number;
  fan_pts_allow_rb?: number;
  fan_pts_allow_te?: number;
  fan_pts_allow_wr?: number;
  fd?: number;
  ff?: number;
  fga?: number;
  fgm?: number;
  fgm_20_29?: number;
  fgm_30_39?: number;
  fgm_40_49?: number;
  fgm_50p?: number;
  fgm_lng?: number;
  fgm_pct?: number;
  fgm_yds?: number;
  fgm_yds_over_30?: number;
  fgmiss?: number;
  fgmiss_30_39?: number;
  fgmiss_40_49?: number;
  fgmiss_50p?: number;
  fum?: number;
  fum_lost?: number;
  fum_rec?: number;
  fum_ret_yd?: number;
  g2g_att?: number;
  g2g_conv?: number;
  g2g_pct?: number;
  gms_active?: number;
  gp?: number;
  gs?: number;
  idp_blk_kick?: number;
  idp_def_td?: number;
  idp_ff?: number;
  idp_fum_rec?: number;
  idp_fum_ret_yd?: number;
  idp_int?: number;
  idp_int_ret_yd?: number;
  idp_pass_def?: number;
  idp_pass_def_3p?: number;
  idp_qb_hit?: number;
  idp_sack?: number;
  idp_sack_yd?: number;
  idp_tkl?: number;
  idp_tkl_ast?: number;
  idp_tkl_loss?: number;
  idp_tkl_solo?: number;
  int?: number;
  int_ret_yd?: number;
  kick_pts?: number;
  kr?: number;
  kr_lng?: number;
  kr_yd?: number;
  kr_ypa?: number;
  off_snp?: number;
  off_yd?: number;
  off_yd_per_play?: number;
  opp_fd?: number;
  opp_off_yd?: number;
  opp_off_yd_per_play?: number;
  opp_pass_fd?: number;
  opp_rush_fd?: number;
  pass_air_yd?: number;
  pass_att?: number;
  pass_cmp?: number;
  pass_cmp_40p?: number;
  pass_fd?: number;
  pass_inc?: number;
  pass_int?: number;
  pass_int_td?: number;
  pass_lng?: number;
  pass_rtg?: number;
  pass_rush_yd?: number;
  pass_rz_att?: number;
  pass_sack?: number;
  pass_sack_yds?: number;
  pass_td?: number;
  pass_td_40p?: number;
  pass_td_50p?: number;
  pass_td_lng?: number;
  pass_yd?: number;
  pass_ypa?: number;
  pass_ypc?: number;
  penalty?: number;
  penalty_yd?: number;
  pos_rank_half_ppr?: number;
  pos_rank_ppr?: number;
  pos_rank_std?: number;
  pr?: number;
  pr_lng?: number;
  pr_yd?: number;
  pr_ypa?: number;
  pts_allow?: number;
  pts_allow_14_20?: number;
  pts_allow_21_27?: number;
  pts_allow_28_34?: number;
  pts_allow_35p?: number;
  pts_allow_7_13?: number;
  pts_half_ppr?: number;
  pts_idp?: number;
  pts_ppr?: number;
  pts_std?: number;
  punt_in_20?: number;
  punt_net_yd?: number;
  punt_tb?: number;
  punt_yds?: number;
  punts?: number;
  qb_hit?: number;
  rec?: number;
  rec_0_4?: number;
  rec_10_19?: number;
  rec_20_29?: number;
  rec_30_39?: number;
  rec_40p?: number;
  rec_5_9?: number;
  rec_air_yd?: number;
  rec_drop?: number;
  rec_fd?: number;
  rec_lng?: number;
  rec_rz_tgt?: number;
  rec_td?: number;
  rec_td_40p?: number;
  rec_td_50p?: number;
  rec_td_lng?: number;
  rec_tgt?: number;
  rec_yar?: number;
  rec_yd?: number;
  rec_ypr?: number;
  rec_ypt?: number;
  rush_40p?: number;
  rush_att?: number;
  rush_btkl?: number;
  rush_fd?: number;
  rush_lng?: number;
  rush_rec_yd?: number;
  rush_rz_att?: number;
  rush_td?: number;
  rush_td_40p?: number;
  rush_td_50p?: number;
  rush_td_lng?: number;
  rush_tkl_loss?: number;
  rush_tkl_loss_yd?: number;
  rush_yac?: number;
  rush_yd?: number;
  rush_ypa?: number;
  rz_att?: number;
  rz_conv?: number;
  rz_pct?: number;
  sack?: number;
  sack_yd?: number;
  st_ff?: number;
  st_fum_rec?: number;
  st_snp?: number;
  st_tkl_solo?: number;
  td?: number;
  tkl?: number;
  tkl_ast?: number;
  tkl_loss?: number;
  tkl_solo?: number;
  tm_def_snp?: number;
  tm_off_snp?: number;
  tm_st_snp?: number;
  xp_blkd?: number;
  xpa?: number;
  xpm?: number;
  xpmiss?: number;
  yds_allow?: number;
  yds_allow_100_199?: number;
  yds_allow_200_299?: number;
  yds_allow_300_349?: number;
  yds_allow_350_399?: number;
  yds_allow_400_449?: number;
  yds_allow_450_499: number | null | undefined
}

export const defaultStats: PlayerStats = {
  id: 0,
  sleeper_player_id: 0,
  playerId: 0,
  year: 2022,
  week: 10,
  blk_kick: 0,
  bonus_fd_qb: 0,
  bonus_fd_rb: 0,
  bonus_fd_te: 0,
  bonus_fd_wr: 0,
  bonus_pass_cmp_25: 0,
  bonus_pass_yd_300: 0,
  bonus_rec_rb: 0,
  bonus_rec_te: 0,
  bonus_rec_wr: 0,
  bonus_rec_yd_100: 0,
  bonus_rush_att_20: 0,
  bonus_rush_rec_yd_100: 0,
  bonus_rush_yd_100: 0,
  bonus_sack_2p: 0,
  bonus_tkl_10p: 0,
  cmp_pct: 0,
  def_3_and_out: 0,
  def_4_and_stop: 0,
  def_forced_punts: 0,
  def_kr: 0,
  def_kr_lng: 0,
  def_kr_yd: 0,
  def_kr_ypa: 0,
  def_pass_def: 0,
  def_pr: 0,
  def_pr_lng: 0,
  def_pr_yd: 0,
  def_pr_ypa: 0,
  def_snp: 0,
  def_st_ff: 0,
  def_st_fum_rec: 0,
  def_st_tkl_solo: 0,
  def_td: 0,
  down_3_att: 0,
  down_3_conv: 0,
  down_3_pct: 0,
  down_4_att: 0,
  down_4_conv: 0,
  down_4_pct: 0,
  fan_pts_allow: 0,
  fan_pts_allow_k: 0,
  fan_pts_allow_qb: 0,
  fan_pts_allow_rb: 0,
  fan_pts_allow_te: 0,
  fan_pts_allow_wr: 0,
  fd: 0,
  ff: 0,
  fga: 0,
  fgm: 0,
  fgm_20_29: 0,
  fgm_30_39: 0,
  fgm_40_49: 0,
  fgm_50p: 0,
  fgm_lng: 0,
  fgm_pct: 0,
  fgm_yds: 0,
  fgm_yds_over_30: 0,
  fgmiss: 0,
  fgmiss_30_39: 0,
  fgmiss_40_49: 0,
  fgmiss_50p: 0,
  fum: 0,
  fum_lost: 0,
  fum_rec: 0,
  fum_ret_yd: 0,
  g2g_att: 0,
  g2g_conv: 0,
  g2g_pct: 0,
  gms_active: 0,
  gp: 0,
  gs: 0,
  idp_blk_kick: 0,
  idp_def_td: 0,
  idp_ff: 0,
  idp_fum_rec: 0,
  idp_fum_ret_yd: 0,
  idp_int: 0,
  idp_int_ret_yd: 0,
  idp_pass_def: 0,
  idp_pass_def_3p: 0,
  idp_qb_hit: 0,
  idp_sack: 0,
  idp_sack_yd: 0,
  idp_tkl: 0,
  idp_tkl_ast: 0,
  idp_tkl_loss: 0,
  idp_tkl_solo: 0,
  int: 0,
  int_ret_yd: 0,
  kick_pts: 0,
  kr: 0,
  kr_lng: 0,
  kr_yd: 0,
  kr_ypa: 0,
  off_snp: 0,
  off_yd: 0,
  off_yd_per_play: 0,
  opp_fd: 0,
  opp_off_yd: 0,
  opp_off_yd_per_play: 0,
  opp_pass_fd: 0,
  opp_rush_fd: 0,
  pass_air_yd: 0,
  pass_att: 0,
  pass_cmp: 0,
  pass_cmp_40p: 0,
  pass_fd: 0,
  pass_inc: 0,
  pass_int: 0,
  pass_int_td: 0,
  pass_lng: 0,
  pass_rtg: 0,
  pass_rush_yd: 0,
  pass_rz_att: 0,
  pass_sack: 0,
  pass_sack_yds: 0,
  pass_td: 0,
  pass_td_40p: 0,
  pass_td_50p: 0,
  pass_td_lng: 0,
  pass_yd: 0,
  pass_ypa: 0,
  pass_ypc: 0,
  penalty: 0,
  penalty_yd: 0,
  pos_rank_half_ppr: 0,
  pos_rank_ppr: 0,
  pos_rank_std: 0,
  pr: 0,
  pr_lng: 0,
  pr_yd: 0,
  pr_ypa: 0,
  pts_allow: 0,
  pts_allow_14_20: 0,
  pts_allow_21_27: 0,
  pts_allow_28_34: 0,
  pts_allow_35p: 0,
  pts_allow_7_13: 0,
  pts_half_ppr: 0,
  pts_idp: 0,
  pts_ppr: 0,
  pts_std: 0,
  punt_in_20: 0,
  punt_net_yd: 0,
  punt_tb: 0,
  punt_yds: 0,
  punts: 0,
  qb_hit: 0,
  rec: 0,
  rec_0_4: 0,
  rec_10_19: 0,
  rec_20_29: 0,
  rec_30_39: 0,
  rec_40p: 0,
  rec_5_9: 0,
  rec_air_yd: 0,
  rec_drop: 0,
  rec_fd: 0,
  rec_lng: 0,
  rec_rz_tgt: 0,
  rec_td: 0,
  rec_td_40p: 0,
  rec_td_50p: 0,
  rec_td_lng: 0,
  rec_tgt: 0,
  rec_yar: 0,
  rec_yd: 0,
  rec_ypr: 0,
  rec_ypt: 0,
  rush_40p: 0,
  rush_att: 0,
  rush_btkl: 0,
  rush_fd: 0,
  rush_lng: 0,
  rush_rec_yd: 0,
  rush_rz_att: 0,
  rush_td: 0,
  rush_td_40p: 0,
  rush_td_50p: 0,
  rush_td_lng: 0,
  rush_tkl_loss: 0,
  rush_tkl_loss_yd: 0,
  rush_yac: 0,
  rush_yd: 0,
  rush_ypa: 0,
  rz_att: 0,
  rz_conv: 0,
  rz_pct: 0,
  sack: 0,
  sack_yd: 0,
  st_ff: 0,
  st_fum_rec: 0,
  st_snp: 0,
  st_tkl_solo: 0,
  td: 0,
  tkl: 0,
  tkl_ast: 0,
  tkl_loss: 0,
  tkl_solo: 0,
  tm_def_snp: 0,
  tm_off_snp: 0,
  tm_st_snp: 0,
  xp_blkd: 0,
  xpa: 0,
  xpm: 0,
  xpmiss: 0,
  yds_allow: 0,
  yds_allow_100_199: 0,
  yds_allow_200_299: 0,
  yds_allow_300_349: 0,
  yds_allow_350_399: 0,
  yds_allow_400_449: 0,
  yds_allow_450_499: 0,
}